### ISSUE TITLE
Add search bar for all tables on all tabs

### ISSUE THREAD

**Issue by biancas20** [CivicDataLab/project-scadl#13]
A search bar to be added on all tables.

**Comment by apoorv74** [comment]
Tables: 

- [ ] - [Top complaint categories across each zone](https://supersetv2.civicdatalab.in/superset/dashboard/p/MGaE0vKdNQ2/)
- [ ] [Complaints from each ward](https://supersetv2.civicdatalab.in/superset/dashboard/p/rzeXp5AWN7P/)
- [ ] [Ward Level Category & Sub Category Wise Complaints](https://supersetv2.civicdatalab.in/superset/dashboard/p/ynvEBn6wEpP/) 
- [ ] [Number of complaints (Co-ordinate wise)](https://supersetv2.civicdatalab.in/superset/dashboard/p/zvrNAPmoXDG/)
- [ ] [Category and Sub Category Wise Complaints](https://supersetv2.civicdatalab.in/superset/dashboard/p/jqxNDAVYbG9/)
