### ISSUE TITLE
Is it possible to add filters on the tables in dashboard so that one can view societies with highest complaints across categories?

### ISSUE THREAD

**Issue by biancas20** [CivicDataLab/project-scadl#14]
Is it possible to add filters on the tables in dashboard so that one can view societies with highest complaints across categories?

**Comment by apoorv74** [comment]
@biancas20 - It is not possible to have a dynamic filter for maps which will show only top `n` values. But the same can be done using the table below the map using the dropdown. 

![image](https://github.com/CivicDataLab/project-scadl/assets/5118689/eea672dc-bf93-4af8-9aae-0387e6d87941)
