### ISSUE TITLE
Add department tab on the dashboard

### ISSUE THREAD

**Issue by biancas20** [CivicDataLab/project-scadl#15]
Add department tab on the dashboard. 

Widgets:

1. Treemap for department-wise complaints
2. Bar graph for department-wise complaint categories
3. Line graph for complaints registered per day (where the user can select one department from a dropdown, and not for overall complaints/all categories)

**Comment by biancas20** [comment]
Widgets:
1. Treemap for department-wise complaints
2. Bar graph for department-wise complaint categories
3. Line graph for complaints registered per day (where the user can select one department from a dropdown, and not for overall complaints/all categories)

**Comment by apoorv74** [comment]
- [ ] Treemap for department-wise complaints
- [ ] Bar graph for department-wise complaint categories
- [ ] Line graph for complaints registered per day

**Comment by apoorv74** [comment]
Widgets added to the Department tab and Updated filter scope

**Comment by biancas20** [comment]
i think the second widget is also a treemap, instead of a bar graph. Can we change this?

**Comment by biancas20** [comment]
Can we add a department filter as well? Will it change too many things on the dashboard?

**Comment by apoorv74** [comment]
Changes:

1. Department filter is added on the society tab
2. Widgets changed in the department tab
