### ISSUE TITLE
Map and Table data not matching

### ISSUE THREAD

**Issue by tauseefsshah** [CivicDataLab/project-scadl#16]
For Naroda ward for the Swaminarayan address the number of complaints is different in the map and different in table

**Comment by apoorv74** [comment]
This is fixed now. Some issue with the filters. @biancas20 please verify.

**Comment by apoorv74** [comment]
If no filters are applied, then the search query on the table does not return rows when there is only one complaint. We can see all the rows when the filters are applied.
