### ISSUE TITLE
Add a widget for bar graph in categories tab with number of complaints on one axis and categories on the other.

### ISSUE THREAD

**Issue by biancas20** [CivicDataLab/project-scadl#17]
It should have one bar for the date range selected and not two bars (for the previous and current week) like how we have for other graphs.

**Comment by apoorv74** [comment]
@biancas20 - Isn't this the same as this graph in the Overview tab - https://supersetv2.civicdatalab.in/superset/dashboard/p/kdMXRAZlEpy/
