### ISSUE TITLE
Add a stacked bar graph (categories stacked) for complaint categories, aggregated at month on Overall tab. 

### ISSUE THREAD

**Issue by biancas20** [CivicDataLab/project-scadl#18]
Example
<img width="453" alt="Screenshot 2024-01-29 at 3 28 39 PM" src="https://github.com/CivicDataLab/project-scadl/assets/71840451/2cdede9e-5ed0-41dc-bace-3a1333a94ba1">

**Comment by apoorv74** [comment]
Chart added here - https://supersetv2.civicdatalab.in/superset/dashboard/p/JBQXmQ9aXV1/
