### ISSUE TITLE
Add a way a user can see the priority complaint category in each ward through the dashboard

### ISSUE THREAD

**Issue by biancas20** [CivicDataLab/project-scadl#19]
Currently i am unable to see one priority complaint for each ward. There should be a widget for this on the 'Ward' tab.

**Comment by apoorv74** [comment]
@biancas20 says  -

Priority complaint - the highest kind of complaint registered within a ward

For example, if Ward A had registered drainage complaints, public lighting complaints and sanitation complaints, but sanitation complaints are the highest among these, then sanitation is a priority complaint for Ward A.

**Comment by apoorv74** [comment]
Add a table with one row per ward. Cols: Zone - Ward - Complaint Category - Percent Complaints
