### ISSUE TITLE
Highlighting repetitive complaints

### ISSUE THREAD

**Issue by apoorv74** [CivicDataLab/project-scadl#23]
This point was discussed in the [previous meeting with SCADL](https://docs.google.com/document/d/1iFIe9wWiGdal0bCz6vDru2kAyvLkW_Fbr8r7VhChxbo/edit). Creating an issue here to discuss probably approaches in which the repeated complaints can be highlighted with the limited number of changes in the current dashboard.

**Comment by biancas20** [comment]
Can we use mobile number along with complaint category and sub-category to identify complaints that are repeated over time? 

May be we can just show this as a table with a frequency count ?

**Comment by apoorv74** [comment]
@biancas20  We have added citizen mobile in both charts (map and table) in the Society Tab. Now the size of the circle depends on the number of complaints from the same mobile number.

**Comment by apoorv74** [comment]
Added another table `Repeat Complaints from Citizens` to search for complaints using mobile number. Note that in most cases there will be more number of complaints here than those seen on the map or the table above as those graphs only contain info where the lat/lng was mapped whereas this table will contain every complaint.

**Comment by apoorv74** [comment]
As suggested by @biancas20 , we have removed the citizen mobile number from all the three charts in the Society tab. Repeat complaints can be identified using the cleaned address col.
