### ISSUE TITLE
Include society names in the complaints map

### ISSUE THREAD

**Issue by tauseefsshah** [CivicDataLab/project-scadl#6]
The SCADL team shared a list of lat lng as per the society names extracted from the address. The same names should be visible on hover on the map.

**Comment by apoorv74** [comment]
Created a new column society name. @tauseefsshah - Please update the chart to include society names on hover.

**Comment by apoorv74** [comment]
Ahmedabad View Port Coordinates - 23.040687, 72.581461

**Comment by apoorv74** [comment]
There are multiple societies for the same lat lon combination. So if we include society names, the number of complaints per society will be less than the number of complaints per lat lon. 

Check this lat lon - 23.0365437 | 72.5611395

**Comment by tauseefsshah** [comment]
![image](https://github.com/CivicDataLab/project-scadl/assets/63847553/4aa56016-f770-4405-965c-0be4e675498e)

**Comment by apoorv74** [comment]
Updated the bubble size and opacity so clusters can be located.

**Comment by apoorv74** [comment]
![image](https://github.com/CivicDataLab/project-scadl/assets/5118689/298bf572-8230-4668-952e-153d3a728082)
