### ISSUE TITLE
Add custom date-range selection and see the complaints during that time

### ISSUE THREAD

**Issue by tauseefsshah** [CivicDataLab/project-scadl#9]
This suggestion came from @biancas20. Currently the data can only be filtered for current and previous week. Can we include a date filter so that the user can filter the data for any time-period?

**Comment by apoorv74** [comment]
Date filter is not working properly for all widgets. We can remove it for now and figure out a better solution for the next phase of the project.

**Comment by apoorv74** [comment]
@tauseefsshah - Please make these changes in the data processing script as well.

**Comment by apoorv74** [comment]
Update: We have added a `Time Period` filter on the dashboard. This filter is compatible with all widgets except the ones where we are displaying results for current/previous week. To do this, we had to change the date format of the `registration_date` col. The new col is titled `registration_date_two` which is of the format - `YYYY-MM-DD`. 

@tauseefsshah - You will have to update the data processing script to make it compatible with the current database.
